version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongomongo
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017
    volumes:
      - db-data:/home/rodrigo/docker/mongo/data/personadb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: mongomongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongomongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

networks: 
    mongo-network:

volumes:
  db-data: