version: '3'
services:

  db:
    image: postgres:11-alpine
    container_name: persona-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rodrigo010"
      POSTGRES_DB: "personas"
    ports:
      - "15432:5432"
      
volumes:
  db-data: