version: '3'
services:

  db:
    image: postgres:11-alpine
    container_name: teste-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "teste123"
      POSTGRES_DB: "teste"
    ports:
      - "15432:5432"
volumes:
  db-data: